"""add card_id and arena_win_rates to cards

Revision ID: 034aa770da13
Revises: ddf10b83cff1
Create Date: 2025-12-11 00:57:10.716621

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '034aa770da13'
down_revision = 'ddf10b83cff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
