"""add card_id and arena_win_rates to cards3

Revision ID: 06299906280e
Revises: f2769ca30bb0
Create Date: 2025-12-11 01:04:02.868237

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '06299906280e'
down_revision = 'f2769ca30bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_id', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('arena_win_rates', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_cards_card_id'), 'cards', ['card_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_card_id'), table_name='cards')
    op.drop_column('cards', 'arena_win_rates')
    op.drop_column('cards', 'card_id')
    # ### end Alembic commands ###
