"""add card_reviews

Revision ID: 447c095270f6
Revises: 198cfb6e7d0f
Create Date: 2025-12-10 23:45:40.568090

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '447c095270f6'
down_revision = '198cfb6e7d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
