"""add card_reviews2

Revision ID: ddf10b83cff1
Revises: 447c095270f6
Create Date: 2025-12-10 23:51:22.525211

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ddf10b83cff1'
down_revision = '447c095270f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('game_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_reviews_card_id'), 'card_reviews', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_reviews_id'), 'card_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_card_reviews_reviewer_id'), 'card_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_reviews_reviewer_id'), table_name='card_reviews')
    op.drop_index(op.f('ix_card_reviews_id'), table_name='card_reviews')
    op.drop_index(op.f('ix_card_reviews_card_id'), table_name='card_reviews')
    op.drop_table('card_reviews')
    # ### end Alembic commands ###
