"""add card_id and arena_win_rates to cards2

Revision ID: f2769ca30bb0
Revises: 034aa770da13
Create Date: 2025-12-11 00:59:51.894455

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f2769ca30bb0'
down_revision = '034aa770da13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
